version: "3.7"
services:

  postgres:
    hostname: postgres
    build:
      context: ./docker-psql/.
    env_file:
      - ./docker-psql/.env
    volumes:
      - ./docker-psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=staco
    ports:
      - "5433:5432"

  localstack:
    image: localstack/localstack:0.13.0
    hostname: localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8090:8090"
    environment:
      - SERVICES=${SERVICES}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8090
      - DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - START_WEB=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
