services:

  postgres:
    hostname: postgres
    build:
      context: ./docker-psql/.
    env_file:
      - ./docker-psql/.env
    volumes:
      - ./docker-psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=staco
    ports:
      - "5432:5432"
    networks:
      staco_net:
        ipv4_address: ${STACO_AWS_POSTGRESQL_IP}

  localstack:
    image: localstack/localstack:0.13.0
    hostname: localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8090:8090"
    environment:
      - SERVICES=${SERVICES}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8090
      - DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - START_WEB=1
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "http://localhost:4566/health"]
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    networks:
      staco_net:
        ipv4_address: ${STACO_AWS_LOCALSTACK_IP}

  aws-cli-1:
    image: amazon/aws-cli:2.4.0
    hostname: aws-cli-1
    container_name: aws-cli-1
    command: ssm --endpoint-url http://${STACO_AWS_LOCALSTACK_IP}:${STACO_AWS_LOCALSTACK_PORT} put-parameter --name /config/StaCoLsService/dev/username --value postgres --type text
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${DEFAULT_REGION}
      - STACO_AWS_LOCALSTACK_IP=${STACO_AWS_LOCALSTACK_IP}
      - STACO_AWS_LOCALSTACK_PORT=${STACO_AWS_LOCALSTACK_PORT}
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      staco_net:
        ipv4_address: ${STACO_AWS_CLI_1_IP}

  aws-cli-2:
    image: amazon/aws-cli:2.4.0
    hostname: aws-cli-2
    container_name: aws-cli-2
    command: ssm --endpoint-url http://${STACO_AWS_LOCALSTACK_IP}:${STACO_AWS_LOCALSTACK_PORT} put-parameter --name /config/StaCoLsService/dev/password --value admin --type text
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${DEFAULT_REGION}
      - STACO_AWS_LOCALSTACK_IP=${STACO_AWS_LOCALSTACK_IP}
      - STACO_AWS_LOCALSTACK_PORT=${STACO_AWS_LOCALSTACK_PORT}
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      staco_net:
        ipv4_address: ${STACO_AWS_CLI_2_IP}

networks:
  staco_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
