version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2023.04.2
    resource_class: large
    steps:
      - checkout
      - run:
          name: Current JDK
          command: java -version

      - run:
          name: Install SDK 17
          command: wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz &&
            tar xvf openjdk-17.0.2_linux-x64_bin.tar.gz &&
            sudo mv jdk-17*/ /opt/jdk17 &&
            export JAVA_HOME=/opt/jdk17 &&
            export PATH=$PATH:$JAVA_HOME/bin

      - run:
          name: Build
          command: export JAVA_HOME=/opt/jdk17 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn -B -DskipTests clean package

      - run:
          name: Test
          command: export JAVA_HOME=/opt/jdk17 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn test

workflows:
  sample:
    jobs:
      - build-and-test
